#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..


if [ "$(uname -s)" == "Darwin" ]
then
    echo "› brew bundle"
    brew bundle
elif [ "$(uname -r)" =~ el([0-9]) ]
then
    sudo dnf install -y tmux 
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

